language: php
php:
 - '7.0'
services:
  - mysql
install:
  - composer install
  - mysql -e "CREATE DATABASE twitchbots"
script:
 - php -l public/index.php
 - php -l api/index.php
 - phpunit --bootstrap vendor/autoload.php test
after_success:
 - source .travis/trust-server.sh
 - ssh humanoid@humanoids.be 'cd dev/twitchbots && git pull && php composer.phar install --no-dev --optimize-autoloader'
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    tags: true
    php: '7.0'
    repo: freaktechnik/twitchbots
