language: php
php:
 - '7.0'
services:
  - mysql
install:
  - composer install
  - mysql -e "CREATE DATABASE twitchbots"
script:
 - php -l public/index.php
 - php -l api/index.php
 - phpunit --bootstrap vendor/autoload.php test
