language: php
php:
 - '7.0'
services:
  - mysql
install:
  - composer install
  - mysql -e "CREATE DATABASE twitchbots"
script:
 - php -l public/index.php
 - php -l api/index.php
 - phpunit --bootstrap vendor/autoload.php test
after_success:
 - eval "$(ssh-agent -s)"
 - openssl aes-256-cbc -K $encrypted_a666911b0f49_key -iv $encrypted_a666911b0f49_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
 - chmod 600 .travis/id_rsa
 - ssh-add .travis/id_rsa
 - ssh humanoid@humanoids.be 'cd dev/twitchbots && git pull'
